project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    theme: spacelab
    comments:
      hypothesis: true
      
  docx: default
  jats: default
  elsevier-pdf: default

bibliography: library.bib


  
