project:
  type: manuscript
  output-dir: docs
  
execute:
  freeze: auto

format:
  html:
    toc: true
    theme: spacelab
    comments:
      hypothesis: true
  docx: default
  elsevier-pdf: 
    fig-pos: "H"

bibliography: library.bib


  
