project:
  type: manuscript
  output-dir: docs
  
execute:
  freeze: auto

format:
  html:
    toc: true
    theme: spacelab
    comments:
      hypothesis: true
  docx: default
  elsevier-pdf: 
    fig-pos: "H"
render: 
  - "!*.qmd"
  - "!*.ipynb"
  - "!*.out.ipynb"
resources:
  - "!*.qmd"
  - "!*.ipynb"
  - "!*.out.ipynb"
  - "!*.embed.ipynb"

bibliography: library.bib


  
