project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    theme: spacelab
    comments:
      hypothesis: true
      
  docx:
    reference-doc: Word_Template.docx
  jats: default
  pdf: default

bibliography: library.bib


  
