---
title: "Replies to reviewers of the 1st round of Remote Sensing"
author: "Simon Oiry"
format: docx
output-file: "Reply_to_reviewers"
---

# Reviewer 1

Overall, this paper presents a solidly researched and theoretically grounded study, offering insights into the types of seagrass bed vegetation and the importance of seagrass bed monitoring. It is a worthwhile document to read. However, there are issues related to uniqueness and experimental organization that, if addressed, could enhance its academic quality.

## Comment 1

Please highlight more clearly the innovations, distinctive features, or unique content of this paper. The work conducted in this paper is indeed sufficiently rigorous, but the unique content or scientific contributions of this work are not yet prominent enough. Since the equipment and methods used in this paper are relatively mature, the distinctive contributions of the current work are not sufficient to support its scientific contributions. Please elaborate and summarize in this regard, and if possible, consider dedicating a separate chapter for a detailed explanation.

### Reply

Thank you for this valuable suggestion. We appreciate your feedback on the need to further highlight the unique contributions and innovations of our study. In response, we have revised the final paragraph of the Introduction (between lines 91 and 108) to more explicitly underscore the distinctive aspects and scientific contributions of our work.

Specifically, we have:

1.  **Clarified the unique contribution of this paper** by emphasizing the broader geographical range and methodological scope of our drone remote sensing application for intertidal habitat mapping, as well as our focus on classifying diverse macrophyte types with high accuracy.

2.  **Highlighted the novelty of our approach in integrating multiple spatial scales** through the simulation of satellite resolutions and quantification of the impact of spatial resolution on classification accuracy, providing a framework to better understand challenges of satellite based-habitat mapping.

3.  **Added a summary of the study's contributions** to contextualize our findings within existing research and underscore the broader implications of this work for coastal habitat mapping.

    We believe these additions better address the innovative aspects of our study and strengthen the scientific contribution of the manuscript.

## Comment 2

### reply

Thank you for your detailed feedback on the classification results presented in Figures 5 to 8. We appreciate your attention to the spectral representations of the Magnoliopsida category in the RGB images. Your observations regarding the varying appearances of pixels classified as seagrass in the RGB images were extremely helpful, as this distinction between different coloration of seagrasses was not sufficiently emphasized in the original manuscript.

In response, we have revised the main text to clarify that the Magnoliopsida class includes pixels with varying spectral signatures due to differences in physiological states, such as leaf health and senescence. These variations are visible in the RGB images, where healthy seagrass leaves appear green, while senescent or altered leaves may appear brown or even white. This variation in seagrass leaf color has been observed during the field campaign by our team.

To ensure accurate classification despite these spectral differences, we carefully included spectral signatures from both healthy and senescent seagrass states in the neural network classifier's training dataset. This approach allowed the classifier to consistently recognize both states as part of the same seagrass class, ensuring that all instances of seagrass, regardless of coloration, are correctly classified as Magnoliopsida.

These modification of the text can be found between lines 194-197 and also between lines 280 and 284.

# Reviewer 2

This study focused on discriminating the seagrass and green macroalgae in the intertidal zone. High-resolution drone image is used for this work which show a higher accuracy in classifying the seagrass and other macrophytes (green algae, brown algae, red algae & diatom). The approach will be helpful to work with satellite image however, several issues should be addressed before this paper can be further considered for acceptance.

## Comment 1

In the "Introduction" part, previous studies on seagrass and macroalgae detection need to be described. Also, prior research using drone on seagrass is not clearly mentioned.

### Reply

Thank you for this suggestion. To address it, we have expanded the Introduction between lines 91 and 93 to include relevant studies on seagrass and macroalgae detection, as well as previous research using drones for seagrass mapping. These additions clarify the context and unique contributions of our study.

## Comment 2

In Table 1, three sites were used for training and other sites were used for validation. However, there are no description what is the features of those 3 sites and why they were selected for training?

### Reply

Thank you for pointing this out. We have updated the manuscript to clarify why these specific sites were selected for training, emphasizing that their 8 mm of resolution allow for an accurate photo interpretation of vegetation classes. Line 146 - 149

## Comment 3

Figure 2 displayed the image for five different classes. However, no clear description on each classes feature are not provided. What is the difference between each class (floating, submerged, or attached to bottom) and how they can by distinguished is not clear. What is the variance for each class. The graph only shows the reflectance value based on the wavelength, but it is not clear which value is used for this graph and how many sample are taken?

### Reply

Thank you for your comments on Figure 2. In response, we have expanded the description of each class in the text to clarify their distinguishing characteristics (Lines 155 - 164). Regarding the spectral shapes shown in Figure 2, we have updated the figure caption to specify that these represent example spectral signatures that are characteristic of each class

## Comment 4

Seagrass color can be varied from green to brown based on the vegetation condition. Then what process is followed to distinguish from both green and brown macroalgae.

### Reply

Thank you for this accurate observation. In response, we have revised the main text to clarify that the Magnoliopsida class includes pixels with varying spectral signatures due to differences in physiological states, such as leaf health and senescence. These variations are visible in the RGB images, where healthy seagrass leaves appear green, while senescent or altered leaves may appear brown or even white. This variation in seagrass leaf color has been observed during the field campaign by our team.

To ensure accurate classification despite these spectral differences, we carefully included spectral signatures from both healthy and senescent seagrass states in the neural network classifier's training dataset. This approach allowed the classifier to consistently recognize both states as part of the same seagrass class, ensuring that all instances of seagrass, regardless of coloration, are correctly classified as Magnoliopsida.

These modification of the text can be found between lines 194-197 and also between lines 280 and 284.

## Comment 5

Description on the diatom classification (Figure 2(E)) is not clear. What is the dimension of diatom or the biofilm they produced.

### Reply

Thank you for your comment. To address this, we have added clarification about the biofilm extent in the main text (Line 156- 157) and included scales in each image of Figure 2 to improve clarity.

## Comment 6

In Figure 3, 'photo interpret polygons' is mentioned without the prior description on it.

### Reply

Thank you for pointing this out. The term "photo-interpret polygons" in Figure 3 was potentially misleading, as it had not been introduced earlier in the text. We have replaced it with "training polygons" in Figure 3, and have clarified the process of creating these polygons in the text (Line 189).

## Comment 7

For each class, along with the scientific name and taxonomic description the general name should be added for easy understanding.

### Reply

Thank you for your feedback. In the original manuscript, both taxonomic and common names for vegetation types were used inconsistently. To improve consistency, we have replaced taxonomic names with common names wherever possible throughout the text. Additionally, we have added a new column in Table 2 to display both the taxonomic and common names for each vegetation class.

## Comment 8

It is mentioned, 7 different classes were categorized for training but in Table 2, information on 5 classes are provided

### Reply

Thank you for your observation. You are correct; the missing classes could have been confusing for readers. We have now added these classes to Table 2 for completeness.

## Comment 9

What kind of variables are used as predictors and description on those variables is required. How many variables are used (20 or 21)?

### Reply

As described in Line 198 - 201, 21 variables were used as predictors for the model, including:

-   10 raw reflectance spectral bands,

-   The same 10 bands standardized, and

-   The Normalized Difference Vegetation Index (NDVI).

## Comment 10

Why the Equation 1 and 2 are used is not clear? The main purpose of both equation and their value need to be mentioned.

### Reply

Equations 1 and 2 were applied to the raw spectral data from the drone to generate the 10 standardized reflectance bands (Equation 1) and the NDVI (Equation 2), which were used as predictors for the model. You can find this information line 198 - 203

## Comment 11

Resampling was conducted to evaluate the influence of spatial resolution on classification. However, no description on the resampling resolution is provided.

### Reply

Thank you for pointing this out. You are absolutely right; these details were overlooked in the original manuscript. We have revised the text at Line 249 to include this clarification.

## Comment 12

In the classification figure, making a visual difference between the sediment class & Phaeophyceae class is difficult due to similar color pattern.

### Reply

Thank you for highlighting this issue. The color scale of the classification maps has been adjusted to improve the distinction between sediment and brown algae, addressing a key concern in the previous maps.

## Comment 13

For validation, how sensitivity, specificity and accuracy are calculated need to be mentioned by using equation.

### Reply

Thank you for your suggestion. The equations used to compute accuracy metrics have been added to the Materials and Methods section (Line 231 - 234) for clarity.

## Comment 14

The figure caption need to be revised. The abbreviation used in figure caption need to be elaborated such as in Figure 11 'GLM predictions'. 

### Reply

Thank you for your suggestion. We have added descriptions for all acronyms used in the figure captions for clarity.

## 

## 
